language: python
python:
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

services: 
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({task:"math homework", desc:"do the math homework you nerd", priority:8, type:"School", checked:"false", date:""});'
  - mongo mydb_test --eval 'db.createUser({task:"chores for me mum", desc:"why do i have to do laundry again", priority:0, type:"House Work", checked:"false", date:""});'